### ISSUE TITLE
Email addresses

### ISSUE THREAD

**Issue by emersonveenstra** [CodeVine/codevine.io#1]
Calling all @CodeVine/homework-planner-owners and @CodeVine/homework-planner-peers (I'll move teams around once we know what we're doing), I need to know what email address you want (if you want one). Just comment here and let me know. You can have a few that are aliases, which means people can send to them and they will go to your main email, but you can only send from your main email. For example, emerson@codevine.io, webmaster@codevine.io, postmaster@codevine.io and irc@codevine.io will all get delivered to emerson@codevine.io, but I can only send from emerson@codevine.io. 

So comment and let me know what emails you want, and I'll set them up whenever I get a chance. I'll email you your passwords and instructions when I get them set up.

**Comment by jacobbuettner** [comment]
jake.buettner

**Comment by Colin-** [comment]
CS@codevine.io

**Comment by ghost** [comment]
andrew.ware

**Comment by jsleathe12295** [comment]
Jonathan. Leathe

On Oct 29, 2014 11:15 AM, Emerson Veenstra notifications@github.com wrote:

Calling all @CodeVine/homework-planner-ownershttps://github.com/orgs/CodeVine/teams/homework-planner-owners and @CodeVine/homework-planner-peershttps://github.com/orgs/CodeVine/teams/homework-planner-peers (I'll move teams around once we know what we're doing), I need to know what email address you want (if you want one). Just comment here and let me know. You can have a few that are aliases, which means people can send to them and they will go to your main email, but you can only send from your main email. For example, emerson@codevine.iomailto:emerson@codevine.io, webmaster@codevine.iomailto:webmaster@codevine.io, postmaster@codevine.iomailto:postmaster@codevine.io and irc@codevine.iomailto:irc@codevine.io will all get delivered to emerson@codevine.iomailto:emerson@codevine.io, but I can only send from emerson@codevine.iomailto:emerson@codevine.io.

So comment and let me know what emails you want, and I'll set them up whenever I get a chance. I'll email you your passwords and instructions when I get them set up.

##

**Comment by emersonveenstra** [comment]
+1 to colin for being original haha
